//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loggly.Config
{
    
    
    /// <summary>
    /// The LogglyAppConfig Configuration Section.
    /// </summary>
    internal partial class LogglyAppConfig : global::System.Configuration.ConfigurationSection
    {
        
        #region Singleton Instance
        /// <summary>
        /// The XML name of the LogglyAppConfig Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string LogglyAppConfigSectionName = "loggly";
        
        /// <summary>
        /// The XML path of the LogglyAppConfig Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string LogglyAppConfigSectionPath = "loggly";
        
        /// <summary>
        /// Gets the LogglyAppConfig instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public static global::Loggly.Config.LogglyAppConfig Instance
        {
            get
            {
                return ((global::Loggly.Config.LogglyAppConfig)(global::System.Configuration.ConfigurationManager.GetSection(global::Loggly.Config.LogglyAppConfig.LogglyAppConfigSectionPath)));
            }
        }
        #endregion
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.LogglyAppConfig.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::Loggly.Config.LogglyAppConfig.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region CustomerToken Property
        /// <summary>
        /// The XML name of the <see cref="CustomerToken"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string CustomerTokenPropertyName = "customerToken";
        
        /// <summary>
        /// Gets or sets the CustomerToken.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The CustomerToken.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.LogglyAppConfig.CustomerTokenPropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual string CustomerToken
        {
            get
            {
                return ((string)(base[global::Loggly.Config.LogglyAppConfig.CustomerTokenPropertyName]));
            }
            set
            {
                base[global::Loggly.Config.LogglyAppConfig.CustomerTokenPropertyName] = value;
            }
        }
        #endregion
        
        #region ApplicationName Property
        /// <summary>
        /// The XML name of the <see cref="ApplicationName"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string ApplicationNamePropertyName = "applicationName";
        
        /// <summary>
        /// Gets or sets the ApplicationName.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The ApplicationName.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.LogglyAppConfig.ApplicationNamePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string ApplicationName
        {
            get
            {
                return ((string)(base[global::Loggly.Config.LogglyAppConfig.ApplicationNamePropertyName]));
            }
            set
            {
                base[global::Loggly.Config.LogglyAppConfig.ApplicationNamePropertyName] = value;
            }
        }
        #endregion
        
        #region ThrowExceptions Property
        /// <summary>
        /// The XML name of the <see cref="ThrowExceptions"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string ThrowExceptionsPropertyName = "throwExceptions";
        
        /// <summary>
        /// Gets or sets the ThrowExceptions.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The ThrowExceptions.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.LogglyAppConfig.ThrowExceptionsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual bool ThrowExceptions
        {
            get
            {
                return ((bool)(base[global::Loggly.Config.LogglyAppConfig.ThrowExceptionsPropertyName]));
            }
            set
            {
                base[global::Loggly.Config.LogglyAppConfig.ThrowExceptionsPropertyName] = value;
            }
        }
        #endregion
        
        #region IsEnabled Property
        /// <summary>
        /// The XML name of the <see cref="IsEnabled"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string IsEnabledPropertyName = "isEnabled";
        
        /// <summary>
        /// Gets or sets the IsEnabled.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The IsEnabled.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.LogglyAppConfig.IsEnabledPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false, DefaultValue=true)]
        public virtual bool IsEnabled
        {
            get
            {
                return ((bool)(base[global::Loggly.Config.LogglyAppConfig.IsEnabledPropertyName]));
            }
            set
            {
                base[global::Loggly.Config.LogglyAppConfig.IsEnabledPropertyName] = value;
            }
        }
        #endregion
        
        #region Tags Property
        /// <summary>
        /// The XML name of the <see cref="Tags"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string TagsPropertyName = "tags";
        
        /// <summary>
        /// Gets or sets the Tags.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Tags.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.LogglyAppConfig.TagsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::Loggly.Config.TagAppConfig Tags
        {
            get
            {
                return ((global::Loggly.Config.TagAppConfig)(base[global::Loggly.Config.LogglyAppConfig.TagsPropertyName]));
            }
            set
            {
                base[global::Loggly.Config.LogglyAppConfig.TagsPropertyName] = value;
            }
        }
        #endregion
        
        #region Search Property
        /// <summary>
        /// The XML name of the <see cref="Search"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string SearchPropertyName = "search";
        
        /// <summary>
        /// Gets or sets the Search.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Search.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.LogglyAppConfig.SearchPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::Loggly.Config.SearchAppConfig Search
        {
            get
            {
                return ((global::Loggly.Config.SearchAppConfig)(base[global::Loggly.Config.LogglyAppConfig.SearchPropertyName]));
            }
            set
            {
                base[global::Loggly.Config.LogglyAppConfig.SearchPropertyName] = value;
            }
        }
        #endregion
        
        #region Transport Property
        /// <summary>
        /// The XML name of the <see cref="Transport"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string TransportPropertyName = "transport";
        
        /// <summary>
        /// Gets or sets the Transport.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Transport.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.LogglyAppConfig.TransportPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::Loggly.Config.TransportAppConfig Transport
        {
            get
            {
                return ((global::Loggly.Config.TransportAppConfig)(base[global::Loggly.Config.LogglyAppConfig.TransportPropertyName]));
            }
            set
            {
                base[global::Loggly.Config.LogglyAppConfig.TransportPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace Loggly.Config
{
    
    
    /// <summary>
    /// A collection of ComplexTagAppConfig instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::Loggly.Config.ComplexTagAppConfig), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::Loggly.Config.ComplexTagCollection.ComplexTagAppConfigPropertyName)]
    internal partial class ComplexTagCollection : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::Loggly.Config.ComplexTagAppConfig"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string ComplexTagAppConfigPropertyName = "tag";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override string ElementName
        {
            get
            {
                return global::Loggly.Config.ComplexTagCollection.ComplexTagAppConfigPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::Loggly.Config.ComplexTagCollection.ComplexTagAppConfigPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::Loggly.Config.ComplexTagAppConfig)(element)).Type;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::Loggly.Config.ComplexTagAppConfig"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::Loggly.Config.ComplexTagAppConfig"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::Loggly.Config.ComplexTagAppConfig();
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::Loggly.Config.ComplexTagAppConfig"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="tag">The <see cref="global::Loggly.Config.ComplexTagAppConfig"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public void Add(global::Loggly.Config.ComplexTagAppConfig tag)
        {
            base.BaseAdd(tag);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::Loggly.Config.ComplexTagAppConfig"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="tag">The <see cref="global::Loggly.Config.ComplexTagAppConfig"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public void Remove(global::Loggly.Config.ComplexTagAppConfig tag)
        {
            base.BaseRemove(this.GetElementKey(tag));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::Loggly.Config.ComplexTagAppConfig"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::Loggly.Config.ComplexTagAppConfig"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::Loggly.Config.ComplexTagAppConfig GetItemAt(int index)
        {
            return ((global::Loggly.Config.ComplexTagAppConfig)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::Loggly.Config.ComplexTagAppConfig"/> with the specified key.
        /// </summary>
        /// <param name="type">The key of the <see cref="global::Loggly.Config.ComplexTagAppConfig"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::Loggly.Config.ComplexTagAppConfig GetItemByKey(string type)
        {
            return ((global::Loggly.Config.ComplexTagAppConfig)(base.BaseGet(((object)(type)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace Loggly.Config
{
    
    
    /// <summary>
    /// The ComplexTagAppConfig Configuration Element.
    /// </summary>
    internal partial class ComplexTagAppConfig : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Type Property
        /// <summary>
        /// The XML name of the <see cref="Type"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string TypePropertyName = "type";
        
        /// <summary>
        /// Gets or sets the Type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Type.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.ComplexTagAppConfig.TypePropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string Type
        {
            get
            {
                return ((string)(base[global::Loggly.Config.ComplexTagAppConfig.TypePropertyName]));
            }
            set
            {
                base[global::Loggly.Config.ComplexTagAppConfig.TypePropertyName] = value;
            }
        }
        #endregion
        
        #region Assembly Property
        /// <summary>
        /// The XML name of the <see cref="Assembly"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string AssemblyPropertyName = "assembly";
        
        /// <summary>
        /// Gets or sets the Assembly.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Assembly.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.ComplexTagAppConfig.AssemblyPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Assembly
        {
            get
            {
                return ((string)(base[global::Loggly.Config.ComplexTagAppConfig.AssemblyPropertyName]));
            }
            set
            {
                base[global::Loggly.Config.ComplexTagAppConfig.AssemblyPropertyName] = value;
            }
        }
        #endregion
        
        #region Formatter Property
        /// <summary>
        /// The XML name of the <see cref="Formatter"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string FormatterPropertyName = "formatter";
        
        /// <summary>
        /// Gets or sets the Formatter.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Formatter.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.ComplexTagAppConfig.FormatterPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Formatter
        {
            get
            {
                return ((string)(base[global::Loggly.Config.ComplexTagAppConfig.FormatterPropertyName]));
            }
            set
            {
                base[global::Loggly.Config.ComplexTagAppConfig.FormatterPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace Loggly.Config
{
    
    
    /// <summary>
    /// A collection of SimpleTagAppConfig instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::Loggly.Config.SimpleTagAppConfig), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::Loggly.Config.SimpleTagCollection.SimpleTagAppConfigPropertyName)]
    internal partial class SimpleTagCollection : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::Loggly.Config.SimpleTagAppConfig"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string SimpleTagAppConfigPropertyName = "tag";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override string ElementName
        {
            get
            {
                return global::Loggly.Config.SimpleTagCollection.SimpleTagAppConfigPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::Loggly.Config.SimpleTagCollection.SimpleTagAppConfigPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::Loggly.Config.SimpleTagAppConfig)(element)).Value;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::Loggly.Config.SimpleTagAppConfig"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::Loggly.Config.SimpleTagAppConfig"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::Loggly.Config.SimpleTagAppConfig();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::Loggly.Config.SimpleTagAppConfig"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::Loggly.Config.SimpleTagAppConfig"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::Loggly.Config.SimpleTagAppConfig this[int index]
        {
            get
            {
                return ((global::Loggly.Config.SimpleTagAppConfig)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::Loggly.Config.SimpleTagAppConfig"/> with the specified key.
        /// </summary>
        /// <param name="value">The key of the <see cref="global::Loggly.Config.SimpleTagAppConfig"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::Loggly.Config.SimpleTagAppConfig this[object value]
        {
            get
            {
                return ((global::Loggly.Config.SimpleTagAppConfig)(base.BaseGet(value)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::Loggly.Config.SimpleTagAppConfig"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="tag">The <see cref="global::Loggly.Config.SimpleTagAppConfig"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public void Add(global::Loggly.Config.SimpleTagAppConfig tag)
        {
            base.BaseAdd(tag);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::Loggly.Config.SimpleTagAppConfig"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="tag">The <see cref="global::Loggly.Config.SimpleTagAppConfig"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public void Remove(global::Loggly.Config.SimpleTagAppConfig tag)
        {
            base.BaseRemove(this.GetElementKey(tag));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::Loggly.Config.SimpleTagAppConfig"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::Loggly.Config.SimpleTagAppConfig"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::Loggly.Config.SimpleTagAppConfig GetItemAt(int index)
        {
            return ((global::Loggly.Config.SimpleTagAppConfig)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::Loggly.Config.SimpleTagAppConfig"/> with the specified key.
        /// </summary>
        /// <param name="value">The key of the <see cref="global::Loggly.Config.SimpleTagAppConfig"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::Loggly.Config.SimpleTagAppConfig GetItemByKey(string value)
        {
            return ((global::Loggly.Config.SimpleTagAppConfig)(base.BaseGet(((object)(value)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace Loggly.Config
{
    
    
    /// <summary>
    /// The SimpleTagAppConfig Configuration Element.
    /// </summary>
    internal partial class SimpleTagAppConfig : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Value Property
        /// <summary>
        /// The XML name of the <see cref="Value"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string ValuePropertyName = "value";
        
        /// <summary>
        /// Gets or sets the Value.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Value.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.SimpleTagAppConfig.ValuePropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string Value
        {
            get
            {
                return ((string)(base[global::Loggly.Config.SimpleTagAppConfig.ValuePropertyName]));
            }
            set
            {
                base[global::Loggly.Config.SimpleTagAppConfig.ValuePropertyName] = value;
            }
        }
        #endregion
    }
}
namespace Loggly.Config
{
    
    
    /// <summary>
    /// The TagAppConfig Configuration Element.
    /// </summary>
    internal partial class TagAppConfig : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Simple Property
        /// <summary>
        /// The XML name of the <see cref="Simple"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string SimplePropertyName = "simple";
        
        /// <summary>
        /// Gets or sets the Simple.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Simple.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.TagAppConfig.SimplePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::Loggly.Config.SimpleTagCollection Simple
        {
            get
            {
                return ((global::Loggly.Config.SimpleTagCollection)(base[global::Loggly.Config.TagAppConfig.SimplePropertyName]));
            }
            set
            {
                base[global::Loggly.Config.TagAppConfig.SimplePropertyName] = value;
            }
        }
        #endregion
        
        #region Complex Property
        /// <summary>
        /// The XML name of the <see cref="Complex"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string ComplexPropertyName = "complex";
        
        /// <summary>
        /// Gets or sets the Complex.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Complex.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.TagAppConfig.ComplexPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::Loggly.Config.ComplexTagCollection Complex
        {
            get
            {
                return ((global::Loggly.Config.ComplexTagCollection)(base[global::Loggly.Config.TagAppConfig.ComplexPropertyName]));
            }
            set
            {
                base[global::Loggly.Config.TagAppConfig.ComplexPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace Loggly.Config
{
    
    
    /// <summary>
    /// The TransportAppConfig Configuration Element.
    /// </summary>
    internal partial class TransportAppConfig : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region LogTransport Property
        /// <summary>
        /// The XML name of the <see cref="LogTransport"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string LogTransportPropertyName = "logTransport";
        
        /// <summary>
        /// Gets or sets the LogTransport.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The LogTransport.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.TransportAppConfig.LogTransportPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::Loggly.Config.LogTransport LogTransport
        {
            get
            {
                return ((global::Loggly.Config.LogTransport)(base[global::Loggly.Config.TransportAppConfig.LogTransportPropertyName]));
            }
            set
            {
                base[global::Loggly.Config.TransportAppConfig.LogTransportPropertyName] = value;
            }
        }
        #endregion
        
        #region EndpointHostname Property
        /// <summary>
        /// The XML name of the <see cref="EndpointHostname"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string EndpointHostnamePropertyName = "endpointHostname";
        
        /// <summary>
        /// Gets or sets the EndpointHostname.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The EndpointHostname.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.TransportAppConfig.EndpointHostnamePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string EndpointHostname
        {
            get
            {
                return ((string)(base[global::Loggly.Config.TransportAppConfig.EndpointHostnamePropertyName]));
            }
            set
            {
                base[global::Loggly.Config.TransportAppConfig.EndpointHostnamePropertyName] = value;
            }
        }
        #endregion
        
        #region EndpointPort Property
        /// <summary>
        /// The XML name of the <see cref="EndpointPort"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string EndpointPortPropertyName = "endpointPort";
        
        /// <summary>
        /// Gets or sets the EndpointPort.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The EndpointPort.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.TransportAppConfig.EndpointPortPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual int EndpointPort
        {
            get
            {
                return ((int)(base[global::Loggly.Config.TransportAppConfig.EndpointPortPropertyName]));
            }
            set
            {
                base[global::Loggly.Config.TransportAppConfig.EndpointPortPropertyName] = value;
            }
        }
        #endregion

		#region IsOmitTimestamp Property
		/// <summary>
		/// The XML name of the <see cref="IsOmitTimestamp"/> property.
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
		internal const string IsOmitTimestampPropertyName = "isOmitTimestamp";

		/// <summary>
		/// Gets or sets the IsOmitTimestamp.
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
		[global::System.ComponentModel.DescriptionAttribute("The IsOmitTimestamp.")]
		[global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.TransportAppConfig.IsOmitTimestampPropertyName, IsRequired = false, IsKey = false, IsDefaultCollection = false)]
		public virtual bool IsOmitTimestamp
		{
			get
			{
				return ((bool)(base[global::Loggly.Config.TransportAppConfig.IsOmitTimestampPropertyName]));
			}
			set
			{
				base[global::Loggly.Config.TransportAppConfig.IsOmitTimestampPropertyName] = value;
			}
		}
        #endregion

        #region ForwardedForIp Property
        /// <summary>
        /// The XML name of the <see cref="ForwardedForIp"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string ForwardedForIpPropertyName = "forwardedForIp";

        /// <summary>
        /// Gets or sets the ForwardedForIp.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The ForwardedForIp.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.TransportAppConfig.ForwardedForIpPropertyName, IsRequired = false, IsKey = false, IsDefaultCollection = false)]
        public virtual string ForwardedForIp
        {
            get
            {
                return ((string)(base[global::Loggly.Config.TransportAppConfig.ForwardedForIpPropertyName]));
            }
            set
            {
                base[global::Loggly.Config.TransportAppConfig.ForwardedForIpPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace Loggly.Config
{
    
    
    /// <summary>
    /// The SearchAppConfig Configuration Element.
    /// </summary>
    internal partial class SearchAppConfig : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Account Property
        /// <summary>
        /// The XML name of the <see cref="Account"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string AccountPropertyName = "account";
        
        /// <summary>
        /// Gets or sets the Account.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Account.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.SearchAppConfig.AccountPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Account
        {
            get
            {
                return ((string)(base[global::Loggly.Config.SearchAppConfig.AccountPropertyName]));
            }
            set
            {
                base[global::Loggly.Config.SearchAppConfig.AccountPropertyName] = value;
            }
        }
        #endregion
        
        #region Username Property
        /// <summary>
        /// The XML name of the <see cref="Username"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string UsernamePropertyName = "username";
        
        /// <summary>
        /// Gets or sets the Username.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Username.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.SearchAppConfig.UsernamePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Username
        {
            get
            {
                return ((string)(base[global::Loggly.Config.SearchAppConfig.UsernamePropertyName]));
            }
            set
            {
                base[global::Loggly.Config.SearchAppConfig.UsernamePropertyName] = value;
            }
        }
        #endregion
        
        #region Password Property
        /// <summary>
        /// The XML name of the <see cref="Password"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string PasswordPropertyName = "password";
        
        /// <summary>
        /// Gets or sets the Password.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Password.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.SearchAppConfig.PasswordPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Password
        {
            get
            {
                return ((string)(base[global::Loggly.Config.SearchAppConfig.PasswordPropertyName]));
            }
            set
            {
                base[global::Loggly.Config.SearchAppConfig.PasswordPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace Loggly.Config
{
    
    
    /// <summary>
    /// LogTransport.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
    public enum LogTransport
    {
        
        /// <summary>
        /// Https.
        /// </summary>
        Https,
        
        /// <summary>
        /// SyslogSecure.
        /// </summary>
        SyslogSecure,
        
        /// <summary>
        /// SyslogUdp.
        /// </summary>
        SyslogUdp,
        
        /// <summary>
        /// SyslogTcp.
        /// </summary>
        SyslogTcp,
    }
}
