//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loggly.Config
{
    
    
    /// <summary>
    /// The LogglyAppConfig Configuration Section.
    /// </summary>
    public partial class LogglyAppConfig : global::System.Configuration.ConfigurationSection
    {
        
        #region Singleton Instance
        /// <summary>
        /// The XML name of the LogglyAppConfig Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string LogglyAppConfigSectionName = "loggly";
        
        /// <summary>
        /// The XML path of the LogglyAppConfig Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string LogglyAppConfigSectionPath = "loggly";
        
        /// <summary>
        /// Gets the LogglyAppConfig instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public static global::Loggly.Config.LogglyAppConfig Instance
        {
            get
            {
                return ((global::Loggly.Config.LogglyAppConfig)(global::System.Configuration.ConfigurationManager.GetSection(global::Loggly.Config.LogglyAppConfig.LogglyAppConfigSectionPath)));
            }
        }
        #endregion
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.LogglyAppConfig.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::Loggly.Config.LogglyAppConfig.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region CustomerToken Property
        /// <summary>
        /// The XML name of the <see cref="CustomerToken"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string CustomerTokenPropertyName = "customerToken";
        
        /// <summary>
        /// Gets or sets the CustomerToken.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The CustomerToken.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.LogglyAppConfig.CustomerTokenPropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual string CustomerToken
        {
            get
            {
                return ((string)(base[global::Loggly.Config.LogglyAppConfig.CustomerTokenPropertyName]));
            }
            set
            {
                base[global::Loggly.Config.LogglyAppConfig.CustomerTokenPropertyName] = value;
            }
        }
        #endregion
        
        #region ThrowExceptions Property
        /// <summary>
        /// The XML name of the <see cref="ThrowExceptions"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string ThrowExceptionsPropertyName = "throwExceptions";
        
        /// <summary>
        /// Gets or sets the ThrowExceptions.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The ThrowExceptions.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.LogglyAppConfig.ThrowExceptionsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual bool ThrowExceptions
        {
            get
            {
                return ((bool)(base[global::Loggly.Config.LogglyAppConfig.ThrowExceptionsPropertyName]));
            }
            set
            {
                base[global::Loggly.Config.LogglyAppConfig.ThrowExceptionsPropertyName] = value;
            }
        }
        #endregion
        
        #region Tags Property
        /// <summary>
        /// The XML name of the <see cref="Tags"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string TagsPropertyName = "tags";
        
        /// <summary>
        /// Gets or sets the Tags.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Tags.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.LogglyAppConfig.TagsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::Loggly.Config.Tags Tags
        {
            get
            {
                return ((global::Loggly.Config.Tags)(base[global::Loggly.Config.LogglyAppConfig.TagsPropertyName]));
            }
            set
            {
                base[global::Loggly.Config.LogglyAppConfig.TagsPropertyName] = value;
            }
        }
        #endregion
        
        #region Transport Property
        /// <summary>
        /// The XML name of the <see cref="Transport"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string TransportPropertyName = "transport";
        
        /// <summary>
        /// Gets or sets the Transport.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Transport.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.LogglyAppConfig.TransportPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::Loggly.Config.Transport Transport
        {
            get
            {
                return ((global::Loggly.Config.Transport)(base[global::Loggly.Config.LogglyAppConfig.TransportPropertyName]));
            }
            set
            {
                base[global::Loggly.Config.LogglyAppConfig.TransportPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace Loggly.Config
{
    
    
    /// <summary>
    /// A collection of ComplexTagAppConfig instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::Loggly.Config.ComplexTagAppConfig), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::Loggly.Config.ComplexTagCollection.ComplexTagAppConfigPropertyName)]
    public partial class ComplexTagCollection : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::Loggly.Config.ComplexTagAppConfig"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string ComplexTagAppConfigPropertyName = "complex";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override string ElementName
        {
            get
            {
                return global::Loggly.Config.ComplexTagCollection.ComplexTagAppConfigPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::Loggly.Config.ComplexTagCollection.ComplexTagAppConfigPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::Loggly.Config.ComplexTagAppConfig)(element)).Name;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::Loggly.Config.ComplexTagAppConfig"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::Loggly.Config.ComplexTagAppConfig"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::Loggly.Config.ComplexTagAppConfig();
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::Loggly.Config.ComplexTagAppConfig"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="complex">The <see cref="global::Loggly.Config.ComplexTagAppConfig"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public void Add(global::Loggly.Config.ComplexTagAppConfig complex)
        {
            base.BaseAdd(complex);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::Loggly.Config.ComplexTagAppConfig"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="complex">The <see cref="global::Loggly.Config.ComplexTagAppConfig"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public void Remove(global::Loggly.Config.ComplexTagAppConfig complex)
        {
            base.BaseRemove(this.GetElementKey(complex));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::Loggly.Config.ComplexTagAppConfig"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::Loggly.Config.ComplexTagAppConfig"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::Loggly.Config.ComplexTagAppConfig GetItemAt(int index)
        {
            return ((global::Loggly.Config.ComplexTagAppConfig)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::Loggly.Config.ComplexTagAppConfig"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::Loggly.Config.ComplexTagAppConfig"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::Loggly.Config.ComplexTagAppConfig GetItemByKey(string name)
        {
            return ((global::Loggly.Config.ComplexTagAppConfig)(base.BaseGet(((object)(name)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace Loggly.Config
{
    
    
    /// <summary>
    /// The ComplexTagAppConfig Configuration Element.
    /// </summary>
    public partial class ComplexTagAppConfig : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Name Property
        /// <summary>
        /// The XML name of the <see cref="Name"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string NamePropertyName = "name";
        
        /// <summary>
        /// Gets or sets the Name.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Name.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.ComplexTagAppConfig.NamePropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string Name
        {
            get
            {
                return ((string)(base[global::Loggly.Config.ComplexTagAppConfig.NamePropertyName]));
            }
            set
            {
                base[global::Loggly.Config.ComplexTagAppConfig.NamePropertyName] = value;
            }
        }
        #endregion
        
        #region Assembly Property
        /// <summary>
        /// The XML name of the <see cref="Assembly"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string AssemblyPropertyName = "assembly";
        
        /// <summary>
        /// Gets or sets the Assembly.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Assembly.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.ComplexTagAppConfig.AssemblyPropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual string Assembly
        {
            get
            {
                return ((string)(base[global::Loggly.Config.ComplexTagAppConfig.AssemblyPropertyName]));
            }
            set
            {
                base[global::Loggly.Config.ComplexTagAppConfig.AssemblyPropertyName] = value;
            }
        }
        #endregion
        
        #region Type Property
        /// <summary>
        /// The XML name of the <see cref="Type"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string TypePropertyName = "type";
        
        /// <summary>
        /// Gets or sets the Type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Type.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.ComplexTagAppConfig.TypePropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual string Type
        {
            get
            {
                return ((string)(base[global::Loggly.Config.ComplexTagAppConfig.TypePropertyName]));
            }
            set
            {
                base[global::Loggly.Config.ComplexTagAppConfig.TypePropertyName] = value;
            }
        }
        #endregion
        
        #region Formatter Property
        /// <summary>
        /// The XML name of the <see cref="Formatter"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string FormatterPropertyName = "formatter";
        
        /// <summary>
        /// Gets or sets the Formatter.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Formatter.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.ComplexTagAppConfig.FormatterPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Formatter
        {
            get
            {
                return ((string)(base[global::Loggly.Config.ComplexTagAppConfig.FormatterPropertyName]));
            }
            set
            {
                base[global::Loggly.Config.ComplexTagAppConfig.FormatterPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace Loggly.Config
{
    
    
    /// <summary>
    /// A collection of SimpleTagAppConfig instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::Loggly.Config.SimpleTagAppConfig), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::Loggly.Config.SimpleTagCollection.SimpleTagAppConfigPropertyName)]
    public partial class SimpleTagCollection : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::Loggly.Config.SimpleTagAppConfig"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string SimpleTagAppConfigPropertyName = "tag";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override string ElementName
        {
            get
            {
                return global::Loggly.Config.SimpleTagCollection.SimpleTagAppConfigPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::Loggly.Config.SimpleTagCollection.SimpleTagAppConfigPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::Loggly.Config.SimpleTagAppConfig)(element)).Value;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::Loggly.Config.SimpleTagAppConfig"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::Loggly.Config.SimpleTagAppConfig"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::Loggly.Config.SimpleTagAppConfig();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::Loggly.Config.SimpleTagAppConfig"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::Loggly.Config.SimpleTagAppConfig"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::Loggly.Config.SimpleTagAppConfig this[int index]
        {
            get
            {
                return ((global::Loggly.Config.SimpleTagAppConfig)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::Loggly.Config.SimpleTagAppConfig"/> with the specified key.
        /// </summary>
        /// <param name="value">The key of the <see cref="global::Loggly.Config.SimpleTagAppConfig"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::Loggly.Config.SimpleTagAppConfig this[object value]
        {
            get
            {
                return ((global::Loggly.Config.SimpleTagAppConfig)(base.BaseGet(value)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::Loggly.Config.SimpleTagAppConfig"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="tag">The <see cref="global::Loggly.Config.SimpleTagAppConfig"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public void Add(global::Loggly.Config.SimpleTagAppConfig tag)
        {
            base.BaseAdd(tag);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::Loggly.Config.SimpleTagAppConfig"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="tag">The <see cref="global::Loggly.Config.SimpleTagAppConfig"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public void Remove(global::Loggly.Config.SimpleTagAppConfig tag)
        {
            base.BaseRemove(this.GetElementKey(tag));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::Loggly.Config.SimpleTagAppConfig"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::Loggly.Config.SimpleTagAppConfig"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::Loggly.Config.SimpleTagAppConfig GetItemAt(int index)
        {
            return ((global::Loggly.Config.SimpleTagAppConfig)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::Loggly.Config.SimpleTagAppConfig"/> with the specified key.
        /// </summary>
        /// <param name="value">The key of the <see cref="global::Loggly.Config.SimpleTagAppConfig"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::Loggly.Config.SimpleTagAppConfig GetItemByKey(string value)
        {
            return ((global::Loggly.Config.SimpleTagAppConfig)(base.BaseGet(((object)(value)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace Loggly.Config
{
    
    
    /// <summary>
    /// The SimpleTagAppConfig Configuration Element.
    /// </summary>
    public partial class SimpleTagAppConfig : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Value Property
        /// <summary>
        /// The XML name of the <see cref="Value"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string ValuePropertyName = "value";
        
        /// <summary>
        /// Gets or sets the Value.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Value.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.SimpleTagAppConfig.ValuePropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string Value
        {
            get
            {
                return ((string)(base[global::Loggly.Config.SimpleTagAppConfig.ValuePropertyName]));
            }
            set
            {
                base[global::Loggly.Config.SimpleTagAppConfig.ValuePropertyName] = value;
            }
        }
        #endregion
    }
}
namespace Loggly.Config
{
    
    
    /// <summary>
    /// The Tags Configuration Element.
    /// </summary>
    public partial class Tags : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Simple Property
        /// <summary>
        /// The XML name of the <see cref="Simple"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string SimplePropertyName = "simple";
        
        /// <summary>
        /// Gets or sets the Simple.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Simple.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.Tags.SimplePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::Loggly.Config.SimpleTagCollection Simple
        {
            get
            {
                return ((global::Loggly.Config.SimpleTagCollection)(base[global::Loggly.Config.Tags.SimplePropertyName]));
            }
            set
            {
                base[global::Loggly.Config.Tags.SimplePropertyName] = value;
            }
        }
        #endregion
        
        #region Complex Property
        /// <summary>
        /// The XML name of the <see cref="Complex"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string ComplexPropertyName = "complex";
        
        /// <summary>
        /// Gets or sets the Complex.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Complex.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.Tags.ComplexPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::Loggly.Config.ComplexTagCollection Complex
        {
            get
            {
                return ((global::Loggly.Config.ComplexTagCollection)(base[global::Loggly.Config.Tags.ComplexPropertyName]));
            }
            set
            {
                base[global::Loggly.Config.Tags.ComplexPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace Loggly.Config
{
    
    
    /// <summary>
    /// The Transport Configuration Element.
    /// </summary>
    public partial class Transport : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Http Property
        /// <summary>
        /// The XML name of the <see cref="Http"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string HttpPropertyName = "http";
        
        /// <summary>
        /// Gets or sets the Http.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Http.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.Transport.HttpPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::Loggly.Config.HttpTransport Http
        {
            get
            {
                return ((global::Loggly.Config.HttpTransport)(base[global::Loggly.Config.Transport.HttpPropertyName]));
            }
            set
            {
                base[global::Loggly.Config.Transport.HttpPropertyName] = value;
            }
        }
        #endregion
        
        #region Credentials Property
        /// <summary>
        /// The XML name of the <see cref="Credentials"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string CredentialsPropertyName = "credentials";
        
        /// <summary>
        /// Gets or sets the Credentials.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Credentials.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.Transport.CredentialsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::Loggly.Config.Credentials Credentials
        {
            get
            {
                return ((global::Loggly.Config.Credentials)(base[global::Loggly.Config.Transport.CredentialsPropertyName]));
            }
            set
            {
                base[global::Loggly.Config.Transport.CredentialsPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace Loggly.Config
{
    
    
    /// <summary>
    /// The HttpTransport Configuration Element.
    /// </summary>
    public partial class HttpTransport : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace Loggly.Config
{
    
    
    /// <summary>
    /// The Credentials Configuration Element.
    /// </summary>
    public partial class Credentials : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Username Property
        /// <summary>
        /// The XML name of the <see cref="Username"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string UsernamePropertyName = "username";
        
        /// <summary>
        /// Gets or sets the Username.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Username.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.Credentials.UsernamePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Username
        {
            get
            {
                return ((string)(base[global::Loggly.Config.Credentials.UsernamePropertyName]));
            }
            set
            {
                base[global::Loggly.Config.Credentials.UsernamePropertyName] = value;
            }
        }
        #endregion
        
        #region Password Property
        /// <summary>
        /// The XML name of the <see cref="Password"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string PasswordPropertyName = "password";
        
        /// <summary>
        /// Gets or sets the Password.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Password.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.Credentials.PasswordPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Password
        {
            get
            {
                return ((string)(base[global::Loggly.Config.Credentials.PasswordPropertyName]));
            }
            set
            {
                base[global::Loggly.Config.Credentials.PasswordPropertyName] = value;
            }
        }
        #endregion
        
        #region Domain Property
        /// <summary>
        /// The XML name of the <see cref="Domain"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string DomainPropertyName = "domain";
        
        /// <summary>
        /// Gets or sets the Domain.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Domain.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Loggly.Config.Credentials.DomainPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Domain
        {
            get
            {
                return ((string)(base[global::Loggly.Config.Credentials.DomainPropertyName]));
            }
            set
            {
                base[global::Loggly.Config.Credentials.DomainPropertyName] = value;
            }
        }
        #endregion
    }
}
